package com.jarvis.nextgen;

import android.Manifest;import android.app.*;import android.app.role.RoleManager;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.os.*;import android.provider.Settings;import android.speech.*;import android.speech.tts.TextToSpeech;import android.net.Uri;import com.jarvis.nextgen.DocumentWorkspace;import android.view.*;import android.widget.*;import java.util.*;
import com.jarvis.nextgen.*;import com.jarvis.nextgen.JarvisCoreView;

public final class MainActivity extends Activity implements JarvisOrchestrator.Listener, com.jarvis.nextgen.VoiceEngine.Listener{
 private JarvisCoreView core;private TextView state,transcript,detail;private com.jarvis.nextgen.VoiceEngine voice;private JarvisOrchestrator brain;private OnlineBrain online;private boolean listening;private boolean continuous;private static final int MIC=100;private static final int DOC_PICKER=300;private static final int IMAGE_PICKER=301;private static final int CAMERA_CAPTURE=302;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(2,5,10));getWindow().setNavigationBarColor(Color.rgb(2,5,10));buildUi();brain=new JarvisOrchestrator(this,this);brain.resumePending();online=new OnlineBrain(this);voice=new com.jarvis.nextgen.VoiceEngine(this,this);requestMic();}
 private TextView tv(String text,float size,int color){TextView v=new TextView(this);v.setText(text);v.setTextSize(size);v.setTextColor(color);v.setGravity(Gravity.CENTER);return v;}
 private void buildUi(){FrameLayout root=new FrameLayout(this);root.setBackgroundColor(Color.rgb(2,5,10));core=new JarvisCoreView(this);root.addView(core,new FrameLayout.LayoutParams(-1,-1));LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(28,30,28,24);root.addView(box,new FrameLayout.LayoutParams(-1,-1));
  TextView brand=tv("J A R V I S",13,Color.WHITE);brand.setLetterSpacing(.28f);box.addView(brand,new LinearLayout.LayoutParams(-1,45));
  TextView sub=tv("PERSONAL INTELLIGENCE SYSTEM",9,Color.rgb(110,145,175));sub.setLetterSpacing(.16f);box.addView(sub,new LinearLayout.LayoutParams(-1,30));
  Space s=new Space(this);box.addView(s,new LinearLayout.LayoutParams(1,0,1));
  state=tv("IDLE",11,Color.rgb(110,190,255));state.setLetterSpacing(.12f);box.addView(state,new LinearLayout.LayoutParams(-1,34));
  transcript=tv("Готов к работе",18,Color.WHITE);transcript.setPadding(10,8,10,8);box.addView(transcript,new LinearLayout.LayoutParams(-1,70));
  detail=tv("Голос • локальные инструменты • память",10,Color.rgb(125,155,185));box.addView(detail,new LinearLayout.LayoutParams(-1,34));
  Button photo=button("КАМЕРА / OCR");photo.setOnClickListener(v->showImageChoices());box.addView(photo,new LinearLayout.LayoutParams(-1,48));
  LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER);Button talk=button("ГОВОРИТЬ");talk.setOnClickListener(v->toggleListening());talk.setOnLongClickListener(v->{continuous=!continuous;toast(continuous?"Непрерывный разговор включён.":"Непрерывный разговор выключен.");return true;});Button actions=button("ЗАДАЧИ");actions.setOnClickListener(v->showActions());Button perms=button("ДОСТУП");perms.setOnClickListener(v->showPermissions());Button image=button("ФОТО");image.setOnClickListener(v->showImageChoices());Button settings=button("НАСТРОЙКИ");settings.setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));row.addView(talk,new LinearLayout.LayoutParams(0,58,1));row.addView(actions,new LinearLayout.LayoutParams(0,58,1));row.addView(perms,new LinearLayout.LayoutParams(0,58,1));box.addView(row,new LinearLayout.LayoutParams(-1,68));
  TextView hud=tv("SECURE • LOCAL CORE • READY",9,Color.rgb(90,150,205)); hud.setGravity(Gravity.CENTER); hud.setLetterSpacing(.10f); box.addView(hud,new LinearLayout.LayoutParams(-1,34));
  setContentView(root);}
 private Button button(String t){Button b=new Button(this);b.setText(t);b.setTextColor(Color.WHITE);b.setTextSize(11);b.setAllCaps(false);return b;}
 private void showImageChoices(){new AlertDialog.Builder(this).setTitle("IMAGE INTELLIGENCE").setItems(new String[]{"Сделать фото","Выбрать изображение"},(d,w)->{if(w==0){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.CAMERA},103);return;}Intent i=new Intent(android.provider.MediaStore.ACTION_IMAGE_CAPTURE);if(i.resolveActivity(getPackageManager())!=null)startActivityForResult(i,CAMERA_CAPTURE);else toast("Камера недоступна.");}else{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType("image/*").addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,IMAGE_PICKER);}}).show();}
 private void processImage(Uri uri){try{com.google.mlkit.vision.common.InputImage img=com.google.mlkit.vision.common.InputImage.fromFilePath(this,uri);com.jarvis.nextgen.ImageIntelligenceTool tool=new com.jarvis.nextgen.ImageIntelligenceTool(this);tool.setImage(img);setState(Models.State.THINKING);detail.setText("Распознаю текст на реальном изображении…");new Thread(()->{Models.ToolResult r=tool.execute("распознай текст");runOnUiThread(()->{transcript.setText(r.message());detail.setText(r.success()?"OCR • результат получен":"OCR • обработка не выполнена");setState(r.success()?Models.State.SUCCESS:Models.State.ERROR);voice.speak(r.success()?"Текст распознан.":r.message());});}).start();}catch(Exception e){setState(Models.State.ERROR);detail.setText("Не удалось открыть изображение: "+e.getMessage());}}
 private void requestMic(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},MIC);}
 private void requestAssistantRole(){if(Build.VERSION.SDK_INT>=29){RoleManager rm=getSystemService(RoleManager.class);if(rm!=null&&rm.isRoleAvailable(RoleManager.ROLE_ASSISTANT)){if(rm.isRoleHeld(RoleManager.ROLE_ASSISTANT))toast("JARVIS уже выбран системным Assistant.");else startActivityForResult(rm.createRequestRoleIntent(RoleManager.ROLE_ASSISTANT),101);}else toast("Роль системного Assistant недоступна на этом устройстве.");}else toast("Роль системного Assistant требует Android 10 или новее.");}
 private void toggleListening(){if(listening)stopListening();else startListening();}
 private void startListening(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestMic();return;}listening=true;voice.setContinuous(continuous);voice.start();}
 private void stopListening(){continuous=false;listening=false;voice.setContinuous(false);setState(Models.State.IDLE);}
 @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==CAMERA_CAPTURE){if(resultCode==RESULT_OK&&data!=null&&data.getExtras()!=null){android.graphics.Bitmap bm=(android.graphics.Bitmap)data.getExtras().get("data");try{com.google.mlkit.vision.common.InputImage img=com.google.mlkit.vision.common.InputImage.fromBitmap(bm,0);com.jarvis.nextgen.ImageIntelligenceTool tool=new com.jarvis.nextgen.ImageIntelligenceTool(this);tool.setImage(img);setState(Models.State.THINKING);new Thread(()->{Models.ToolResult r=tool.execute("распознай текст");runOnUiThread(()->{transcript.setText(r.message());detail.setText(r.success()?"OCR • камера":"OCR • ошибка");setState(r.success()?Models.State.SUCCESS:Models.State.ERROR);voice.speak(r.success()?"Текст распознан.":r.message());});}).start();}catch(Exception e){setState(Models.State.ERROR);}}return;}if(requestCode==IMAGE_PICKER){if(resultCode==RESULT_OK&&data!=null&&data.getData()!=null)processImage(data.getData());return;}if(requestCode==DOC_PICKER){if(resultCode!=RESULT_OK||data==null||data.getData()==null){detail.setText("Выбор документа отменён");setState(Models.State.IDLE);return;}Uri uri=data.getData();try{getContentResolver().takePersistableUriPermission(uri,data.getFlags()&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION));}catch(Exception ignored){}setState(Models.State.THINKING);detail.setText("Документ • локальный анализ");new Thread(()->{com.jarvis.nextgen.DocumentIntelligenceTool tool=new com.jarvis.nextgen.DocumentIntelligenceTool(this);tool.setDocument(uri);Models.ToolResult r=tool.execute("проанализируй документ");runOnUiThread(()->{String m=r.message();transcript.setText(m.length()>1800?m.substring(0,1800)+"…":m);detail.setText(r.success()?"Документ • результат проверен":"Документ • обработка не выполнена");setState(r.success()?Models.State.SUCCESS:Models.State.ERROR);voice.speak(r.success()?"Документ обработан.":m);});}).start();}}
 @Override public void onListening(){runOnUiThread(()->{listening=true;setState(Models.State.LISTENING);detail.setText("Слушаю реальный микрофон");});}
 @Override public void onLevel(float level){runOnUiThread(()->core.setAudioLevel(level));}
 @Override public void onSpeech(String text){runOnUiThread(()->{transcript.setText("«"+text+"»");setState(Models.State.THINKING);String l=text.toLowerCase(Locale.ROOT);if(l.contains("проанализируй файл")||l.contains("прочитай файл")||l.contains("проанализируй документ")||l.contains("прочитай документ")){Intent pick=new Intent(Intent.ACTION_OPEN_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType("*/*").addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(pick,DOC_PICKER);}else brain.handle(text);});}
 @Override public void onThinking(){runOnUiThread(()->{listening=false;setState(Models.State.THINKING);});}
 @Override public void onError(int code){runOnUiThread(()->{listening=false;setState(Models.State.ERROR);detail.setText("Ошибка распознавания: "+code);});}
 private void setState(Models.State s){runOnUiThread(()->{state.setText(s.name());core.setState(s.name());});}
 @Override public void state(Models.State s){setState(s);}
 @Override public void reply(String text){runOnUiThread(()->{transcript.setText(text);detail.setText("JARVIS • проверенный результат");setState(Models.State.SPEAKING);voice.speak(text);});}
 @Override public void askConfirmation(String text,Runnable yes,Runnable no){runOnUiThread(()->new AlertDialog.Builder(this).setTitle("JARVIS • подтверждение").setMessage(text).setPositiveButton("ПОДТВЕРДИТЬ",(d,w)->yes.run()).setNegativeButton("ОТМЕНА",(d,w)->no.run()).setNeutralButton("ДОСТУП",(d,w)->showPermissions()).show());}
 private void showActions(){
  StringBuilder s=new StringBuilder(); AgentExecutionStore.Snapshot pending=brain.pendingExecution();
  if(pending!=null && pending.status()!=AgentExecutionStore.Status.COMPLETED && pending.status()!=AgentExecutionStore.Status.FAILED && pending.status()!=AgentExecutionStore.Status.CANCELLED){
    s.append("ТЕКУЩАЯ ЗАДАЧА\n").append(pending.status()).append(" • шаг ").append(pending.nextIndex()+1).append("\n").append(pending.original()).append("\n\n");
  }
  for(var x:new ActionCenter(this).recent())s.append(x.status()).append("  •  ").append(x.title()).append("\n");
  if(s.length()==0)s.append("История задач пуста.");
  AlertDialog.Builder b=new AlertDialog.Builder(this).setTitle("AI ACTION CENTER").setMessage(s.toString()).setPositiveButton("ОК",null);
  if(pending!=null && pending.status()!=AgentExecutionStore.Status.COMPLETED && pending.status()!=AgentExecutionStore.Status.FAILED && pending.status()!=AgentExecutionStore.Status.CANCELLED){
    b.setNegativeButton("ОТМЕНИТЬ",(d,w)->brain.cancelPending());
    if(pending.status()==AgentExecutionStore.Status.PAUSED)b.setNeutralButton("ПРОДОЛЖИТЬ",(d,w)->brain.resumePending());
  }
  b.show();
}
 private void showPermissions(){StringBuilder s=new StringBuilder();s.append("Микрофон: ").append(granted(Manifest.permission.RECORD_AUDIO)?"разрешён":"нужен").append("\n");s.append("Контакты: ").append(granted(Manifest.permission.READ_CONTACTS)?"разрешены":"не выданы").append("\n");s.append("Звонки: ").append(granted(Manifest.permission.CALL_PHONE)?"разрешены":"не выданы").append("\n");s.append("Календарь: ").append(granted(Manifest.permission.READ_CALENDAR)?"разрешён":"не выдан").append("\n");s.append("Камера: ").append(granted(Manifest.permission.CAMERA)?"разрешена":"не выдана").append("\n");s.append("Уведомления: ").append(Build.VERSION.SDK_INT<33||granted(Manifest.permission.POST_NOTIFICATIONS)?"разрешены":"не выданы").append("\n");s.append("Онлайн AI: ").append(online.configured()?"настроен":"не настроен");new AlertDialog.Builder(this).setTitle("PRIVACY / PERMISSIONS").setMessage(s).setPositiveButton("РАЗРЕШЕНИЯ",(d,w)->requestOperationalPermissions()).setNeutralButton("ASSISTANT",(d,w)->requestAssistantRole()).setNegativeButton("УВЕДОМЛЕНИЯ",(d,w)->startActivity(new Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS))).show();}
  private void requestOperationalPermissions(){ if(Build.VERSION.SDK_INT<23)return; ArrayList<String> list=new ArrayList<>(); if(checkSelfPermission(Manifest.permission.READ_CONTACTS)!=PackageManager.PERMISSION_GRANTED)list.add(Manifest.permission.READ_CONTACTS); if(checkSelfPermission(Manifest.permission.CALL_PHONE)!=PackageManager.PERMISSION_GRANTED)list.add(Manifest.permission.CALL_PHONE); if(checkSelfPermission(Manifest.permission.READ_CALENDAR)!=PackageManager.PERMISSION_GRANTED)list.add(Manifest.permission.READ_CALENDAR); if(checkSelfPermission(Manifest.permission.WRITE_CALENDAR)!=PackageManager.PERMISSION_GRANTED)list.add(Manifest.permission.WRITE_CALENDAR); if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)list.add(Manifest.permission.CAMERA); if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)list.add(Manifest.permission.POST_NOTIFICATIONS); if(!list.isEmpty())requestPermissions(list.toArray(new String[0]),102); else toast("Необходимые разрешения уже выданы."); }
 private boolean granted(String p){return Build.VERSION.SDK_INT<23||checkSelfPermission(p)==PackageManager.PERMISSION_GRANTED;}
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
 @Override protected void onDestroy(){if(voice!=null)voice.stop();brain.shutdown();super.onDestroy();}
}
