package com.jarvis.nextgen;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.provider.CalendarContract;import java.util.*;
public final class ProactiveEngine {
 public static final String PREFS="proactive";private static final String ENABLED="enabled";private static final int MORNING=71001,CHECK=71002;private final Context c;private final AlarmManager alarm;private final android.content.SharedPreferences p;
 public ProactiveEngine(Context x){c=x.getApplicationContext();alarm=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);p=c.getSharedPreferences(PREFS,0);} public boolean enabled(){return p.getBoolean(ENABLED,false);} public void enable(){p.edit().putBoolean(ENABLED,true).apply();schedule();} public void disable(){p.edit().putBoolean(ENABLED,false).apply();cancel(MORNING);cancel(CHECK);}
 public void schedule(){if(!enabled()||alarm==null)return;Calendar m=Calendar.getInstance();m.set(Calendar.HOUR_OF_DAY,8);m.set(Calendar.MINUTE,0);m.set(Calendar.SECOND,0);m.set(Calendar.MILLISECOND,0);if(m.getTimeInMillis()<=System.currentTimeMillis())m.add(Calendar.DAY_OF_YEAR,1);set(MORNING,m.getTimeInMillis(),86400000L,"MORNING");set(CHECK,System.currentTimeMillis()+60000L,900000L,"CHECK");}
 private void set(int code,long at,long interval,String type){Intent i=new Intent(c,ProactiveReceiver.class).setAction(ProactiveReceiver.ACTION).putExtra("type",type);PendingIntent pi=PendingIntent.getBroadcast(c,code,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);alarm.setInexactRepeating(AlarmManager.RTC_WAKEUP,at,interval,pi);} private void cancel(int code){Intent i=new Intent(c,ProactiveReceiver.class).setAction(ProactiveReceiver.ACTION);PendingIntent pi=PendingIntent.getBroadcast(c,code,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);alarm.cancel(pi);pi.cancel();}
 public String morningBriefing(){if(c.checkSelfPermission(Manifest.permission.READ_CALENDAR)!=PackageManager.PERMISSION_GRANTED)return "Утренний обзор недоступен: нет доступа к календарю.";Calendar n=Calendar.getInstance();long end=n.getTimeInMillis()+86400000L;int count=0;StringBuilder b=new StringBuilder();try(android.database.Cursor cur=c.getContentResolver().query(CalendarContract.Instances.CONTENT_URI,new String[]{CalendarContract.Instances.EVENT_ID,CalendarContract.Instances.TITLE,CalendarContract.Instances.BEGIN},CalendarContract.Instances.BEGIN+">=? AND "+CalendarContract.Instances.BEGIN+"<?",new String[]{String.valueOf(n.getTimeInMillis()),String.valueOf(end)},CalendarContract.Instances.BEGIN+" ASC")){if(cur!=null)while(cur.moveToNext()&&count<5){if(count++>0)b.append("; ");b.append(cur.getString(1)==null?"Без названия":cur.getString(1));}}catch(Exception e){return "Не удалось получить данные календаря.";}return count==0?"На ближайшие 24 часа событий в календаре не найдено.":"Сегодня: "+b;}
 public String upcoming(){if(c.checkSelfPermission(Manifest.permission.READ_CALENDAR)!=PackageManager.PERMISSION_GRANTED)return null;long now=System.currentTimeMillis(),limit=now+1860000L;try(android.database.Cursor cur=c.getContentResolver().query(CalendarContract.Instances.CONTENT_URI,new String[]{CalendarContract.Instances.EVENT_ID,CalendarContract.Instances.TITLE,CalendarContract.Instances.BEGIN},CalendarContract.Instances.BEGIN+">=? AND "+CalendarContract.Instances.BEGIN+"<=?",new String[]{String.valueOf(now),String.valueOf(limit)},CalendarContract.Instances.BEGIN+" ASC")){if(cur!=null&&cur.moveToFirst()){long id=cur.getLong(0),begin=cur.getLong(2);String key="notified_"+id+"_"+begin;if(p.getBoolean(key,false))return null;p.edit().putBoolean(key,true).apply();long mins=Math.max(1,(begin-now+59999L)/60000L);return "Через "+mins+" мин. событие: "+(cur.getString(1)==null||cur.getString(1).isBlank()?"Без названия":cur.getString(1));}}catch(Exception ignored){}return null;}
}
